DATA SEGMENT
        NUM1 DB 5
        NUM2 DB 9
        NUM3 DB 7
        LRGT DB ?
ENDS
CODE SEGMENT
    ASSUME DS:DATA CS:CODE
START:
    MOV AX,DATA
    MOV DS,AX
    MOV AL,NUM1
    MOV LRGT,AL
    CMP AL,NUM2
    JGE SKIP1
    MOV AL,NUM2
    MOV LRGT,AL
SKIP1:
    MOV AL,LRGT
    CMP AL,NUM3
    JGE SKIP2
    MOV AL,NUM3
    MOV LRGT,AL
SKIP2:
    MOV AH,4CH
    INT 21H
ENDS
END START